#!/usr/bin/env python3
"""
build_app.py — One-click builder.

Run this ONCE on your own computer:
    python build_app.py

Output:
    Windows  →  dist/HospitalBillParser.exe   (share this file)
    Mac      →  dist/HospitalBillParser        (share this file)

Colleagues just double-click — no Python, no installs, nothing.
"""

import os, sys, shutil, subprocess, urllib.request, zipfile, platform
from pathlib import Path

HERE = Path(__file__).parent
TESS_DIR = HERE / "_tesseract_bundle"

# ── Tesseract download sources ────────────────────────────────────────────────
# Portable builds — small, no installer needed
WIN_TESS_URL  = "https://github.com/UB-Mannheim/tesseract/releases/download/v5.3.3.20231005/tesseract-ocr-w64-setup-5.3.3.20231005.exe"
MAC_TESS_URL  = None   # Mac uses brew (handled separately)
TESS_DATA_URL = "https://github.com/tesseract-ocr/tessdata/raw/main/eng.traineddata"

# ─────────────────────────────────────────────────────────────────────────────

def run(cmd, **kw):
    print(f"  > {' '.join(cmd) if isinstance(cmd, list) else cmd}")
    subprocess.run(cmd, check=True, **kw)


def step(msg):
    print(f"\n{'='*60}\n  {msg}\n{'='*60}")


# ── 1. Install Python dependencies ───────────────────────────────────────────
step("Step 1/4 — Installing Python dependencies")
run([sys.executable, "-m", "pip", "install", "--quiet", "--upgrade",
     "pyinstaller", "pdfplumber", "openpyxl", "pytesseract", "pdf2image", "pillow"])


# ── 2. Bundle Tesseract ───────────────────────────────────────────────────────
step("Step 2/4 — Preparing Tesseract OCR bundle")

IS_WIN = sys.platform == "win32"
IS_MAC = sys.platform == "darwin"

if IS_WIN:
    TESS_DIR.mkdir(exist_ok=True)
    tess_exe = TESS_DIR / "tesseract.exe"

    if not tess_exe.exists():
        print("  Downloading Tesseract for Windows (~25 MB)...")
        installer = TESS_DIR / "tess_setup.exe"
        urllib.request.urlretrieve(WIN_TESS_URL, installer)

        # Silent install into TESS_DIR
        print("  Installing silently into bundle folder...")
        run([str(installer), "/S", f"/D={TESS_DIR}"], shell=False)
        installer.unlink(missing_ok=True)
    else:
        print("  Tesseract already downloaded, skipping.")

    # Download English language data if missing
    tessdata_dir = TESS_DIR / "tessdata"
    tessdata_dir.mkdir(exist_ok=True)
    eng_data = tessdata_dir / "eng.traineddata"
    if not eng_data.exists():
        print("  Downloading English OCR data (~12 MB)...")
        urllib.request.urlretrieve(TESS_DATA_URL, eng_data)

    # Collect all Tesseract files for PyInstaller
    tess_datas = []
    for f in TESS_DIR.rglob("*"):
        if f.is_file():
            rel = f.relative_to(TESS_DIR)
            tess_datas.extend(["--add-data", f"{f};tesseract/{rel.parent}"])

elif IS_MAC:
    # Check brew tesseract
    result = subprocess.run(["which", "tesseract"], capture_output=True)
    if result.returncode != 0:
        print("  Installing Tesseract via Homebrew...")
        run(["brew", "install", "tesseract"])

    tess_path = subprocess.run(["which", "tesseract"],
                                capture_output=True, text=True).stdout.strip()
    tess_bin  = Path(tess_path)
    tess_lib  = tess_bin.parent.parent / "lib"
    tess_data = tess_bin.parent.parent / "share" / "tessdata"

    tess_datas = [
        "--add-binary", f"{tess_bin}:tesseract/bin",
        "--add-data",   f"{tess_data}:tesseract/tessdata",
    ]
    # Bundle dylibs
    for dylib in tess_lib.glob("libtesseract*"):
        tess_datas += ["--add-binary", f"{dylib}:tesseract/lib"]
    for dylib in tess_lib.glob("liblept*"):
        tess_datas += ["--add-binary", f"{dylib}:tesseract/lib"]

else:
    print("  Linux: assuming tesseract is installed system-wide.")
    tess_datas = []


# ── 3. Generate runtime hook so app finds bundled Tesseract ──────────────────
step("Step 3/4 — Writing runtime configuration")

hook = HERE / "_hook_tesseract.py"
hook.write_text("""\
# This file is auto-generated by build_app.py
# It tells pytesseract where to find the bundled Tesseract at runtime.
import sys, os
from pathlib import Path

def get_tesseract_path():
    if getattr(sys, 'frozen', False):
        # Running inside PyInstaller bundle
        base = Path(sys._MEIPASS)
        if sys.platform == 'win32':
            exe = base / 'tesseract' / 'tesseract.exe'
        else:
            exe = base / 'tesseract' / 'bin' / 'tesseract'
        if exe.exists():
            os.environ['TESSDATA_PREFIX'] = str(base / 'tesseract' / 'tessdata')
            return str(exe)
    return 'tesseract'   # fall back to system install
""")

# Patch app.py imports to call the hook
app_src = (HERE / "app.py").read_text()
hook_inject = "import _hook_tesseract as _th\nimport pytesseract as _pt\n_pt.pytesseract.tesseract_cmd = _th.get_tesseract_path()\n"
if "_hook_tesseract" not in app_src:
    patched = app_src.replace(
        "import sys\n",
        "import sys\n" + hook_inject,
        1
    )
    # Write a build-time copy so we don't permanently modify app.py
    build_app = HERE / "_app_build.py"
    build_app.write_text(patched)
    entry_point = "_app_build.py"
else:
    entry_point = "app.py"


# ── 4. Run PyInstaller ────────────────────────────────────────────────────────
step("Step 4/4 — Building executable")

# Clean previous build
for d in ["build", "dist"]:
    if (HERE / d).exists():
        shutil.rmtree(HERE / d)

cmd = [
    sys.executable, "-m", "PyInstaller",
    "--onefile",
    "--windowed",
    "--name", "HospitalBillParser",
    "--add-data", f"parser.py{';' if IS_WIN else ':'}.",
    "--add-data", f"_hook_tesseract.py{';' if IS_WIN else ':'}.",
    "--hidden-import", "pdfplumber",
    "--hidden-import", "openpyxl",
    "--hidden-import", "pytesseract",
    "--hidden-import", "pdf2image",
    "--hidden-import", "PIL",
] + tess_datas + [entry_point]

run(cmd, cwd=HERE)

# Clean up temp files
for tmp in ["_app_build.py", "_hook_tesseract.py"]:
    (HERE / tmp).unlink(missing_ok=True)

# ── Done ──────────────────────────────────────────────────────────────────────
ext  = ".exe" if IS_WIN else ""
dist = HERE / "dist" / f"HospitalBillParser{ext}"
print(f"""
{'='*60}
  ✓  BUILD COMPLETE!

  Your shareable file:
  {dist}

  Just send this ONE file to your colleagues.
  They double-click it — no installs needed.
{'='*60}
""")
